openapi: 3.0.0
servers:
  - url: https://foot-api-server.com
info:
  version: latest
  title: PROG3 - TD2
paths:
  /matches:
    get:
      tags:
        - Matches
      summary: Get all matches
      operationId: getMatches
      responses:
        '200':
          description: List of Matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
  /matches/{id}:
    get:
      tags:
        - Matches
      summary: Get match by id
      operationId: getMatchById
      responses:
        '200':
          description: the identified match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
  /matches/{matchId}/goals:
    post:
      tags:
        - Matches
      summary: score goals on a match
      parameters:
        - name: matchId
          in: path
          schema:
            type: integer
          required: true
      description: note that a player with `isGuardian=true` won't be able to score
      operationId: addGoals
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Scorer'
      responses:
        '200':
          description: The updated match with new scores
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
  /players:
    post:
      tags:
        - players
      summary: add players
      description: add new players
      operationId: addPlayers
      parameters:
        - name: teamId
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreatePlayer'
      responses:
        '200':
          description: list of the added players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    put:
      tags:
        - players
      summary: Edit players
      description: |
        edit players, the id must be provided
      operationId: editPlayers
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: The updated players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
components:
  schemas:
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Player:
      properties:
        id:
          type: integer
        allOf:
          $ref: "#/components/schemas/CreatePlayer"
    CreatePlayer:
      properties:
        name:
          type: string
        isGuardian:
          type: boolean
    Match:
      type: object
      properties:
        id:
          type: integer
        datetime:
          type: string
          format: datetime
        stadium:
          type: string
        teamA:
          allOf:
            - $ref: '#/components/schemas/PlayedTeam'
        teamB:
          allOf:
            - $ref: '#/components/schemas/PlayedTeam'
    PlayedTeam:
      type: object
      properties:
        team:
          $ref: '#/components/schemas/Team'
        goals:
          type: integer
        scorers:
          type: array
          items:
            $ref: '#/components/schemas/Scorer'
    Scorer:
      type: object
      properties:
        player:
          $ref: '#/components/schemas/Player'
        isOG:
          type: boolean
        scoreTime:
          type: integer